### PR TITLE
added fuzz script for afl

### PR DESCRIPTION
**Pull request by tesch1**
Saw this on hackernews, I just happened to be playing with fuzzing lately, this seemed like a good candidate :o)

So far just found a crash due to testre.cpp.

### CODE REVIEW

**Comment by arnoldrobbins** [comment]
Hi. Would you be kind enough to move the fuzzing script into a new 'contrib' directory?  There's no real reason for it to be in the same directory as the main source files.  For extra credit you can add a README.md listing yourself (name + email) as author of the script.  I suspect other things will end up in that directory over time.

I've briefly reviewed your changes and they look reasonable. I want to make another pass before merging but don't anticipate any issues.

Thank you for your interest!

**Comment by tesch1** [comment]
Well, thanks for sharing this piece of the canon!  It's wonderful.  Love seeing "26 years ago" on the commits.

Happy to oblige... let me know if there's anything else I can change.

**Comment by arnoldrobbins** [comment]
Much thanks.  What I hope is my last request: Please update the ChangeLog too. THANKS!

**Comment by tesch1** [comment]
Voila.

**Comment by arnoldrobbins** [comment]
Merged into my master. Much thanks!

**Pull request merged**
