### PR TITLE
all: fix C++ code + tests

### PR DESCRIPTION
**Pull request by rsc**

### CODE REVIEW

**Comment by rsc** [comment]
After this sequence of commits, `make retest greptest sedtest` passes.

**Comment by arnoldrobbins** [comment]
This is all wonderful.  Would it be imposing to much to ask you to update the ChangeLog too?  if yes, then I'll do it.  Thanks!

**Comment by rsc** [comment]
Added ChangeLog edits to each commit and squashed the two sed pointer fixes into one commit.

**Comment by rsc** [comment]
Sorry, I s/Add/Added/ in previous comment but not fast enough for GitHub to send the right mail. :-)

**Comment by arnoldrobbins** [comment]
Much thanks!

**Pull request merged**
